# backend/alembic/script.py.mako
"""Initial migration

Revision ID: e9f619bf4619
Revises: 
Create Date: 2026-01-02 10:41:05.990043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9f619bf4619'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meals', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('meals', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('meals', 'calories',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_meals_created_at'), 'meals', ['created_at'], unique=False)
    op.create_index(op.f('ix_meals_id'), 'meals', ['id'], unique=False)
    op.drop_constraint(op.f('meals_user_id_fkey'), 'meals', type_='foreignkey')
    op.create_foreign_key(None, 'meals', 'users', ['user_id'], ['id'])
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'meals', type_='foreignkey')
    op.create_foreign_key(op.f('meals_user_id_fkey'), 'meals', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_meals_id'), table_name='meals')
    op.drop_index(op.f('ix_meals_created_at'), table_name='meals')
    op.alter_column('meals', 'calories',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('meals', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('meals', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###